# docker-compose.yml - Complete NEETS Bridge Setup
version: '3.8'

services:
  neets-bridge:
    build: .
    container_name: neets-bridge
    restart: unless-stopped
    ports:
      - "8080:8080"  # WebSocket port for Stream Deck
      - "3000:3000"  # Optional: Web interface port
    environment:
      - NEETS_HOST=${NEETS_HOST:-192.168.10.109}
      - NEETS_PORT=${NEETS_PORT:-5000}
      - WS_PORT=${WS_PORT:-8080}
      - WEB_PORT=${WEB_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    networks:
      - neets-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neets-bridge.rule=Host(`neets-bridge.local`)"
      - "traefik.http.services.neets-bridge.loadbalancer.server.port=3000"

  # Optional: Web interface for debugging and control
  neets-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: neets-web
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - BRIDGE_WS_URL=ws://neets-bridge:8080
      - REACT_APP_BRIDGE_WS_URL=ws://localhost:8080
    depends_on:
      - neets-bridge
    networks:
      - neets-network

  # Optional: MQTT broker for additional integrations
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: neets-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - neets-network

  # Optional: InfluxDB for logging and analytics
  influxdb:
    image: influxdb:2.7-alpine
    container_name: neets-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=neets
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=neetsbridge123
    volumes:
      - influx-data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      - neets-network

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: neets-grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=neetsbridge123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - neets-network

networks:
  neets-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  influx-data:
  grafana-data:
