version: '3.8'

services:
  neets-bridge:
    build: .
    container_name: neets-bridge
    ports:
      - "3000:3000"
    environment:
      - NEETS_IP=192.168.10.109
      - NEETS_PORT=5000
      - SERVER_PORT=3000
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
